# -*- mode: ruby -*-
# vi: set ft=ruby :

HTTP_PORT = 8080

# Synced folder inside the VM
LOCAL_PC_PATH = ".."
MOUNTED_VM_PATH = "/var/www/roc-alliance-mgmt"

Vagrant.configure("2") do |config|

  config.vm.box = "geerlingguy/ubuntu2004"

  config.vm.hostname = "ubuntu-vagrant"

  # Forward HTTP port.
  config.vm.network "forwarded_port", guest: 80, host: HTTP_PORT, host_ip: "0.0.0.0"

  # Prevent vagrant asking everytime by specifying the interface on you PC, for example:
  #config.vm.network "public_network", bridge: "eth0"

  # This mounts LOCAL_PC_PATH directly from local files on your PC. 
  config.vm.synced_folder LOCAL_PC_PATH, MOUNTED_VM_PATH

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine (useful for troubleshooting).
    #vb.gui = true
    vb.memory = "768"

    # Disable Audio and USB in VirtualBox (may prevent having to install add-ons on your PC).
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.customize ["modifyvm", :id, "--usb", "off"]
  end

  # Set timezone to America/Toronto
  config.vm.provision "shell", inline: <<-END
    sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/America/Toronto /etc/localtime
  END

  # Setup Apache
  config.vm.provision "shell", path: "setup.sh", args: MOUNTED_VM_PATH

  # Easier web development with everything under vagrant user
  config.vm.provision "shell", inline: <<-END
    sed -i 's/APACHE_RUN_USER=.*/APACHE_RUN_USER=vagrant/g' /etc/apache2/envvars
    sed -i 's/APACHE_RUN_GROUP=.*/APACHE_RUN_GROUP=vagrant/g' /etc/apache2/envvars
    systemctl restart apache2
  END

  # Install dependencies with composer (without being root)
  config.vm.provision "shell", privileged: false, args: MOUNTED_VM_PATH, inline: <<-END
    cd $1/composer
    composer install 2>&1
  END

  config.vm.post_up_message = <<-END
  ---------------------------------------------------------------
   Web app available at: http://127.0.0.1:#{HTTP_PORT}
  ---------------------------------------------------------------
  END

end
